### ISSUE TITLE
Create blob containing double quotes fails

### ISSUE THREAD

**Issue by twcclegg** [octokit/octokit.net#1052]
Trying to create a blob that contains double quotes (") fails:
```c#
await Client.GitDatabase.Blob.Create(Owner, repo, new NewBlob {Content = "﻿<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<configuration xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />\r\n" });
```
This returns a sha but when trying to make a tree based on this blob I get error that that sha is not a valid blob.

**Comment by devkhan** [comment]
Can you post the stack trace?

**Comment by twcclegg** [comment]
```
   at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 563
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 545
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 530
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__17`1.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReleaseTool.GitHub.<CreateTreeForBlob>d__22.MoveNext() in C:\Users\tclegg.OFFICE\Documents\GitHub\ReleaseTool\GitHub.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReleaseTool.GitHub.<CreateCommitForBlob>d__23.MoveNext() in C:\Users\tclegg.OFFICE\Documents\GitHub\ReleaseTool\GitHub.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReleaseTool.GitHub.<UpdateConfigTemplate>d__33.MoveNext() in C:\Users\tclegg.OFFICE\Documents\GitHub\ReleaseTool\GitHub.cs:line 252
```

**Comment by devkhan** [comment]
This doesn't show the exact exception, can you post the complete stack trace including the exception that is thrown?

**Comment by twcclegg** [comment]
It is throwing out of the first if in HandleErrors in Connection.cs https://github.com/octokit/octokit.net/blob/master/Octokit/Http/Connection.cs#L578

response:
```
-		response	{Octokit.Internal.Response}	Octokit.IResponse {Octokit.Internal.Response}
-		ApiInfo	{Octokit.ApiInfo}	Octokit.ApiInfo
+		AcceptedOauthScopes	Count = 0	System.Collections.Generic.IReadOnlyList<string> {System.Collections.ObjectModel.ReadOnlyCollection<string>}
		Etag	null	string
+		Links	Count = 0	System.Collections.Generic.IReadOnlyDictionary<string, System.Uri> {System.Collections.ObjectModel.ReadOnlyDictionary<string, System.Uri>}
+		OauthScopes	Count = 3	System.Collections.Generic.IReadOnlyList<string> {System.Collections.ObjectModel.ReadOnlyCollection<string>}
+		RateLimit	Limit 5000, Remaining 4961, Reset 03/04/2016 20:29:31 +00:00 	Octokit.RateLimit
		Body	"{\"message\":\"tree.sha 0180e978c65bdba55f6a2021c6f0a3a94a2cf9df is not a valid blob\",\"documentation_url\":\"https://developer.github.com/v3/git/trees/#create-a-tree\"}"	object {string}
		ContentType	"application/json"	string
-		Headers	Count = 17	System.Collections.Generic.IReadOnlyDictionary<string, string> {System.Collections.ObjectModel.ReadOnlyDictionary<string, string>}
+		[0]	{[Status, 422 Unprocessable Entity]}	System.Collections.Generic.KeyValuePair<string, string>
+		[1]	{[X-RateLimit-Limit, 5000]}	System.Collections.Generic.KeyValuePair<string, string>
+		[2]	{[X-RateLimit-Remaining, 4961]}	System.Collections.Generic.KeyValuePair<string, string>
+		[3]	{[X-RateLimit-Reset, 1457123371]}	System.Collections.Generic.KeyValuePair<string, string>
+		[4]	{[X-OAuth-Scopes, gist, repo, user]}	System.Collections.Generic.KeyValuePair<string, string>
+		[5]	{[X-Accepted-OAuth-Scopes, ]}	System.Collections.Generic.KeyValuePair<string, string>
+		[6]	{[X-GitHub-Media-Type, github.v3; param=quicksilver-preview; format=json]}	System.Collections.Generic.KeyValuePair<string, string>
+		[7]	{[Access-Control-Expose-Headers, ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval]}	System.Collections.Generic.KeyValuePair<string, string>
+		[8]	{[Access-Control-Allow-Origin, *]}	System.Collections.Generic.KeyValuePair<string, string>
+		[9]	{[Content-Security-Policy, default-src 'none']}	System.Collections.Generic.KeyValuePair<string, string>
+		[10]	{[Strict-Transport-Security, max-age=31536000; includeSubdomains; preload]}	System.Collections.Generic.KeyValuePair<string, string>
+		[11]	{[X-Content-Type-Options, nosniff]}	System.Collections.Generic.KeyValuePair<string, string>
+		[12]	{[X-Frame-Options, deny]}	System.Collections.Generic.KeyValuePair<string, string>
+		[13]	{[X-XSS-Protection, 1; mode=block]}	System.Collections.Generic.KeyValuePair<string, string>
+		[14]	{[X-GitHub-Request-Id, CF0878E2:16F34:3D34B0E:56D9E2E7]}	System.Collections.Generic.KeyValuePair<string, string>
+		[15]	{[Date, Fri, 04 Mar 2016 19:32:57 GMT]}	System.Collections.Generic.KeyValuePair<string, string>
+		[16]	{[Server, GitHub.com]}	System.Collections.Generic.KeyValuePair<string, string>
+		Raw View		
		StatusCode	422	System.Net.HttpStatusCode
```
exceptionFunc:
```
-		exceptionFunc	{Method = {System.Exception <.cctor>b__59_1(Octokit.IResponse)}}	System.Func<Octokit.IResponse, System.Exception>
+		Method	{System.Exception <.cctor>b__59_1(Octokit.IResponse)}	System.Reflection.MethodInfo {System.Reflection.RuntimeMethodInfo}
		Target	{Octokit.Connection.<>c}	object {Octokit.Connection.<>c}
+		_invocationCount	{0}	System.IntPtr
		_invocationList	null	object
+		_methodBase	{System.Exception <.cctor>b__59_1(Octokit.IResponse)}	object {System.Reflection.RuntimeMethodInfo}
+		_methodPtr	{4877544}	System.IntPtr
+		_methodPtrAux	{0}	System.IntPtr
		_target	{Octokit.Connection.<>c}	object {Octokit.Connection.<>c}
```

**Comment by devkhan** [comment]
Just a guess, can you try explicitly specifying the encoding, e.g. ```"utf-8"``` of the ```NewBlob``` ?

**Comment by twcclegg** [comment]
Adding ``Encoding = EncodingType.Utf8`` to the NewBlob did not cause any change in behavior.

**Comment by devkhan** [comment]
Well, I'm not sure on this, but the GitHub API is responding with a 422 Unprocessable Entity Status, Octokit is just throwing exception because of the 422, therefore, it must be a problem with the GitHub API.

Maybe someone inside GitHub can help, @shiftkey ?

**Comment by shiftkey** [comment]
This is the interesting bit:

> This returns a sha but when trying to make a tree based on this blob I get error that that sha is not a valid blob.

I could put together a test to reproduce this issue (for example, [something like this](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/TreeClientTests.cs#L23-L46)) but I'd love to see a sample from @twcclegg about how he is creating the tree - the blob contents might not be the root cause here....

**Comment by devkhan** [comment]
Also, the error message says:

> ```tree.sha 0180e978c65bdba55f6a2021c6f0a3a94a2cf9df is not a valid blob.```

Can you try manually making a request to respective API-endpoint to check whether the given blob actually exists or not?

And, @shiftkey how about changing [this test](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/TreeClientTests.cs#L58) instead to include an escaped ```"``` (it will test the exact scenario)?

**Comment by shiftkey** [comment]
This test works for me

```csharp
[IntegrationTest]
public async Task CanCreateATreeWithXml()
{
    var blob = new NewBlob
    {
        Content = "﻿<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<configuration xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />\r\n",
        Encoding = EncodingType.Utf8
    };

    var createdBlob = await _github.Git.Blob.Create(_context.RepositoryOwner, _context.RepositoryName, blob);

    var newTree = new NewTree();
    newTree.Tree.Add(new NewTreeItem
    {
        Type = TreeType.Blob,
        Path = "foo.xml",
        Sha = createdBlob.Sha,
        Mode = FileMode.File
    });

    var result = await _fixture.Create(_context.RepositoryOwner, _context.RepositoryName, newTree);

    Assert.NotNull(result);
}
```

You can see the created tree here: https://api.github.com/repos/shiftkey-tester/public-repo-20160306095953730/git/trees/710653b5331f19af77762c86d5adafda81a4b052

**Comment by devkhan** [comment]
So, it means the problem might be in the way @twcclegg is calling the API?

**Comment by shiftkey** [comment]
@devkhan possibly - I'd love a sample to see how @twcclegg's usage differs from mine...

**Comment by twcclegg** [comment]
I will look tomorrow into simplifying my usage and provide a test that reproduces the issue. Thanks.

**Comment by twcclegg** [comment]
In trying to reduce my code to the minimum I unintentionally somehow changed something such that the test started passing. Closing this issue. Thanks again.
