### ISSUE TITLE
Deserialization crash with duplicate dictionary key in Events api

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1683]
Not sure if there is too much we can do about this but I thought I would raise it, as I sporadically run into this error.  

This is targetting GitHub Enterprise 2.8.7 using the latest  (0.26) Octokit.net

The following line of code
``` csharp
var events = await this.GitHubClient.Issue.Events.GetAllForIssue(owner, repository, issue.Number);
```

Sometimes throws the following exception inside Octokit, but when re-running against the same repo/issue it does not occur again, thus it is proving hard to track down!  I also ran a test in a loop overnight and still could not get a repro!  I really want to see the json response from the server to see if there actually is a duplicate field in the response or whether it is some kind of timing issue with the internal deserialization logic

```
System.ArgumentException : An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 126
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 1478
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 165
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 1505
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 165
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 583
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 595
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 21
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in D:\repos\octokit.net\Octokit\Http\JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__54`1.MoveNext() in D:\repos\octokit.net\Octokit\Http\Connection.cs:line 574
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<GetPage>d__41`1.MoveNext() in D:\repos\octokit.net\Octokit\Http\ApiConnection.cs:line 589
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext() in D:\repos\octokit.net\Octokit\Http\ApiConnection.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in D:\repos\octokit.net\Octokit\Clients\ApiPagination.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by ryangribble** [comment]
Looking into this a bit more I think it's because my calling application is running various tasks in parallel - it must be hitting a timing issue with the `Dictionary<Type, Dictionary<object, object>> _cachedEnums` from `GitHubSerializerStrategy` of which we have a static instance in `SimpleJsonSerializer`!  `static readonly GitHubSerializerStrategy _serializationStrategy = new GitHubSerializerStrategy();` thus making it not threadsafe.

in  which isn't threadsafe.  

Tracing through the code, `if (_cachedEnums[type].ContainsKey(value))` is returning `false` but when it then attempts to `_cachedEnums[type].Add(value, parsed);` it throws the exception that the key already esxists (another thread has just put it in there).

It seems an easy fix would be to change `_cachedEnums`to the `ThreadsafeDictionary` helper class like other parts of `SimpleJson` are using (or we could use the framework's `ConcurrentDictionary`)

**Comment by ryangribble** [comment]
Interestingly it looks like [this unit test run](https://ci.appveyor.com/project/github-windows/octokit-net/build/0.29.0-PullRequest.1713+2.build.2389) just ran into this issue

**Comment by daveaglick** [comment]
I am also seeing this on other endpoints like repositories and issues. Also running queries in parallel via a `Task.WhenAll()` call.

**Comment by ryangribble** [comment]
Yep it doesn't matter which endpoints as it's related to the internals of the deserializer class.  The workaround at the moment is to use separate instances of `GitHubClient` for each thread.  The proper fix is to implement thread safe dictionaries which I hope to get to when I have a chance (but PR's are very much welcome as well! 😀 )

**Comment by daveaglick** [comment]
I'm game for a PR. My instinct is to use the `ConcurrentDictionary` class to handle this. I also think the cache will need to use thread-safe dictionaries as it's values since those sub-dictionaries are also potentially accessed concurrently.

Let me know if you think I should be using `ReflectionUtils.ThreadSafeDictionary` instead. It looks like it's optimized for computing new values for a specific key on get misses. It appears it assumes that every key has one corresponding correct value that can be computed by a delegate (I.e., a dictionary that maps types to their constructor - a given type has a specific constructor). If I'm understanding it correctly, that doesn't seem like an ideal fit here.
