### ISSUE TITLE
If used in IL-merged assembly, GetVersionInformation crashes octokit connection

### ISSUE THREAD

**Issue by Licho1** [octokit/octokit.net#1782]
We are building single executable using ilmerge.
After we do this, octokit crashes with:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Octokit.Connection.GetVersionInformation()
   at Octokit.Connection.FormatUserAgent(ProductHeaderValue productInformation)
   at Octokit.Connection..ctor(ProductHeaderValue productInformation, Uri baseAddress, ICredentialStore credentialStore, IHttpClient httpClient, IJsonSerializer serializer)
   at Octokit.Connection..ctor(ProductHeaderValue productInformation, Uri baseAddress, ICredentialStore credentialStore)
```

It is due to bug here:

```
private static string _versionInformation;
        static string GetVersionInformation()
        {
            if (string.IsNullOrEmpty(_versionInformation))
            {
                _versionInformation = typeof(IGitHubClient)
                    .GetTypeInfo()
                    .Assembly
                    .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                    .InformationalVersion;
            }

            return _versionInformation;
        }
```

**Comment by ryangribble** [comment]
Hi @Licho1,

Would this be because your assembly doesn't have an `InformationalVersionAttribute` set or is it not even possible to work around?

**Comment by Licho1** [comment]
It indeed is because the final assembly is missing and AssemblyInformationalVersion and you can add this attribute to your assembly as a workaround.

**Comment by shiftkey** [comment]
Marking this one as a bug, but because there's a workaround and plenty of other work I'm not sure when we'll get to it.

**Comment by TopazTK** [comment]
Not to necro or anything, but since this is still open I will concur:
As of 02/21/22, this is still present.
