### ISSUE TITLE
Inviting user to a repo throws exception

### ISSUE THREAD

**Issue by davidhouweling** [octokit/octokit.net#1785]
Octokit: 0.29.0
.NET: 4.6.1

When calling the following:
``` csharp
var result = client.Repository.Collaborator.Invite(accountName, repoName, gitHubUsername, new CollaboratorRequest(Permission.Push)).Result;
```

I'm receiving the following exception, but running my .NET application through Fiddler I am seeing the request to GitHub perform successfully, as well as the invitation get received successfully.

However, it looks like it does 2 calls for the invite, the first is successful (but then there is most likely something within Octokit not handling it accordingly) and then another reattempt, before throwing.

```
String was not recognized as a valid DateTime.
at System.DateTimeParse.ParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, TimeSpan& offset)
at System.DateTimeOffset.ParseExact(String input, String[] formats, IFormatProvider formatProvider, DateTimeStyles styles)
at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
at Octokit.Connection.d__56`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Octokit.ApiConnection.d__28`1.MoveNext()
```

**Comment by ryangribble** [comment]
Hi @davidhouweling 

If you're running it through fiddler are you able to post the json response so we can check it against the response object model? Obviously it's a date field but there are a few in the response so would be easy to see exactly which one it is... 

The mention of 2 calls being made is also interesting, as we do not have any built in retries or anything like that... Could you please post the fiddler details of those too?

**Comment by davidhouweling** [comment]
Hi @ryangribble thanks for getting back to me so promptly.

Fiddler response received:
``` JSON
{"id":8207388,"repository":{"id":125925210,"name":"repo_for_david.houweling-thetrainline.com","full_name":"trainlinerecruitment/repo_for_david.houweling-thetrainline.com","owner":{"login":"trainlinerecruitment","id":30077446,"avatar_url":"https://avatars1.githubusercontent.com/u/30077446?v=4","gravatar_id":"","url":"https://api.github.com/users/trainlinerecruitment","html_url":"https://github.com/trainlinerecruitment","followers_url":"https://api.github.com/users/trainlinerecruitment/followers","following_url":"https://api.github.com/users/trainlinerecruitment/following{/other_user}","gists_url":"https://api.github.com/users/trainlinerecruitment/gists{/gist_id}","starred_url":"https://api.github.com/users/trainlinerecruitment/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/trainlinerecruitment/subscriptions","organizations_url":"https://api.github.com/users/trainlinerecruitment/orgs","repos_url":"https://api.github.com/users/trainlinerecruitment/repos","events_url":"https://api.github.com/users/trainlinerecruitment/events{/privacy}","received_events_url":"https://api.github.com/users/trainlinerecruitment/received_events","type":"Organization","site_admin":false},"private":true,"html_url":"https://github.com/trainlinerecruitment/repo_for_david.houweling-thetrainline.com","description":null,"fork":false,"url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com","forks_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/forks","keys_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/keys{/key_id}","collaborators_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/teams","hooks_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/hooks","issue_events_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/issues/events{/number}","events_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/events","assignees_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/assignees{/user}","branches_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/branches{/branch}","tags_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/tags","blobs_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/git/refs{/sha}","trees_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/git/trees{/sha}","statuses_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/statuses/{sha}","languages_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/languages","stargazers_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/stargazers","contributors_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/contributors","subscribers_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/subscribers","subscription_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/subscription","commits_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/commits{/sha}","git_commits_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/git/commits{/sha}","comments_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/comments{/number}","issue_comment_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/issues/comments{/number}","contents_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/contents/{+path}","compare_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/compare/{base}...{head}","merges_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/merges","archive_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/downloads","issues_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/issues{/number}","pulls_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/pulls{/number}","milestones_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/milestones{/number}","notifications_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/labels{/name}","releases_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/releases{/id}","deployments_url":"https://api.github.com/repos/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/deployments"},"invitee":{"login":"davidhouweling","id":9696959,"avatar_url":"https://avatars0.githubusercontent.com/u/9696959?v=4","gravatar_id":"","url":"https://api.github.com/users/davidhouweling","html_url":"https://github.com/davidhouweling","followers_url":"https://api.github.com/users/davidhouweling/followers","following_url":"https://api.github.com/users/davidhouweling/following{/other_user}","gists_url":"https://api.github.com/users/davidhouweling/gists{/gist_id}","starred_url":"https://api.github.com/users/davidhouweling/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidhouweling/subscriptions","organizations_url":"https://api.github.com/users/davidhouweling/orgs","repos_url":"https://api.github.com/users/davidhouweling/repos","events_url":"https://api.github.com/users/davidhouweling/events{/privacy}","received_events_url":"https://api.github.com/users/davidhouweling/received_events","type":"User","site_admin":false},"inviter":{"login":"thetrainconductor","id":2421357,"avatar_url":"https://avatars2.githubusercontent.com/u/2421357?v=4","gravatar_id":"","url":"https://api.github.com/users/thetrainconductor","html_url":"https://github.com/thetrainconductor","followers_url":"https://api.github.com/users/thetrainconductor/followers","following_url":"https://api.github.com/users/thetrainconductor/following{/other_user}","gists_url":"https://api.github.com/users/thetrainconductor/gists{/gist_id}","starred_url":"https://api.github.com/users/thetrainconductor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/thetrainconductor/subscriptions","organizations_url":"https://api.github.com/users/thetrainconductor/orgs","repos_url":"https://api.github.com/users/thetrainconductor/repos","events_url":"https://api.github.com/users/thetrainconductor/events{/privacy}","received_events_url":"https://api.github.com/users/thetrainconductor/received_events","type":"User","site_admin":false},"permissions":"write","created_at":"2018-03-19T21:55:16.620+00:00","url":"https://api.github.com/user/repository_invitations/8207388","html_url":"https://github.com/trainlinerecruitment/repo_for_david.houweling-thetrainline.com/invitations"}
```

Interesting I didn't see the second call this time. In any case, this JSON file will help.

**Comment by shiftkey** [comment]
@davidhouweling the problem seems to be this value:

```
"created_at": "2018-03-19T21:55:16.620+00:00",
```

That's different to other datetime formats that the GitHub API returns:

```
  "created_at": "2016-05-11T15:59:00Z",
  "updated_at": "2018-03-19T20:39:05Z",
  "pushed_at": "2018-03-19T18:26:49Z",
```

**Comment by davidhouweling** [comment]
Interesting, i guess this needs to be taken into account? I am calling github.com so it isn't an enterprise based issue.

**Comment by shiftkey** [comment]
@davidhouweling please reach out to https://github.com/contact and point them at this discussion - I think it's a bug with this particular endpoint.

**Comment by davidhouweling** [comment]
@shiftkey I have sent them a message as requested. Shall we give it a few days and see if they get back to us accordingly?

I wonder, given GitHub is a reliable enough source, is there a reason we are so strict on the parsing in [the code](https://github.com/octokit/octokit.net/blob/master/Octokit/SimpleJson.cs#L1390) and not just use `DateTime.Parse` and let the internal .NET engine determine the value?

**Comment by shiftkey** [comment]
> is there a reason we are so strict on the parsing in the code and not just use `DateTime.Parse` and let the internal .NET engine determine the value?

We're strict because [the GitHub API docs](https://developer.github.com/v3/#timezones) clearly document the format of datetime values with timezone offsets, and I believe this is something that needs to be fixed on the server.

**Comment by davidhouweling** [comment]
Yes it seems there is a bit of confusion on the GitHub side as the documentation is saying that it would look like the UTC style, but the link they point to as an example is the Zulu style.

**Comment by ryangribble** [comment]
Also (and im struggling to remember the complete ins and outs of it) I think I found that `DateTime.Parse` actually didnt fully honour some of the formatting we receive from GitHub formatted dates (around the "Z" character I think).  Ill see if i can find a discussion

**Comment by shiftkey** [comment]
@davidhouweling can you retest this? I think we've fixed the datetime formatting on this endpoint so that it's now consistent with the others.

**Comment by davidhouweling** [comment]
Closing as GitHub said they've resolved this. Will reopen if I encounter again.
