### ISSUE TITLE
IIssuesLabelClient.RemoveFromIssue started returning "Error parsing JSON"

### ISSUE THREAD

**Issue by MylioBill** [octokit/octokit.net#1865]
NuGet package v0.31.0

I have code that uses IIssuesLabelClient.RemoveFromIssue(string owner, string name, int number, string labelName)  

Everything has been working fine until a couple days ago, when this method started throwing Bad Request 400: Error Parsing JSON API exceptions.  This happens on any issue when removing any existing label. Adding labels works fine.

**Comment by ryangribble** [comment]
Hi @MylioBill I haven't had a chance to attempt to repro this myself yet as I've been on mobile only.

Given there's been no updates I'd guess this is an upstream github API change - the question is whether it's intentional or not. 

You said removing existing labels fails but adding labels works. Does adding a label and then trying to remove it, result in the same behaviour? 

Out of interest, do these labels in question have emojis in them, or the description field set at all?

**Comment by MylioBill** [comment]
Adding a label, then removing it results in the exception.  No emojis or descriptions in the labels that have the issue.

**Comment by MylioBill** [comment]
Stack info in case it's useful

```
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<Delete>d__37`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MylioGitHub.GitHub.<RemoveLabelFromIssue>d__23.MoveNext() in C:\Git\Mylio\tools\Github\Triage\Triage\GitHub.cs:line 260
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MylioGitHub.MylioGitHubForm.<ApplyLabels>d__51.MoveNext() in C:\Git\Mylio\tools\Github\Triage\Triage\MylioGitHubForm.cs:line 781
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MylioGitHub.MylioGitHubForm.<BtnApply_Click>d__55.MoveNext() in C:\Git\Mylio\tools\Github\Triage\Triage\MylioGitHubForm.cs:line 836
```

**Comment by ryangribble** [comment]
Cool, I found out what the problem is here.  Turns out we were accidentally passing a string preview header into the `Delete()` method as a message body.  This has been the case for sometime and been working OK (I ran these integration tests just a few days ago myself) so something on github.com must have changed where it is validating the body of the DELETE request instead of ignoring it as it must have done previously.

https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Http/IApiConnection.cs#L329


I will put a fix in the next build but in the meantime you could probably use the `client.Issue.Update()` method to update your issue and remove the label

**Comment by MylioBill** [comment]
Using IssueUpdate sidesteps the issue. Thanks!
