### ISSUE TITLE
Retrieving events for issue throws System.OverflowException

### ISSUE THREAD

**Issue by matt-richardson** [octokit/octokit.net#1939]
I'm using Octokit version `0.29.0`, and I've just starting hitting an exception retrieving events for an issue:

```
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy)
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json)
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
   at Octokit.Connection.<Run>d__56`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<GetPage>d__41`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
```

when calling:
```
var @events = await gitHubClient.Issue.Events.GetAllForIssue(repository.Owner, repository.Name, issueNumber);
```

It appears that the events have an id greater than `int32.MaxValue` - `#event-2148215177`.

Looks very similar to https://github.com/octokit/octokit.net/issues/1702. I wonder if a review needs to be made of `int` id's?

PR incoming.

**Comment by ryangribble** [comment]
Yeah we use `long` for id fields on new response classes but something older ones could potentially do with an update. I was actually trying to get info from github internally about which id's were 32bit and which were 64bit but this discussion reminds me I never did get the list 🤣
