### ISSUE TITLE
Retrieving events throws Stack.Overflow exception.

### ISSUE THREAD

**Issue by bobbytreed** [octokit/octokit.net#1979]
In the lastest local build (0.33.0), I still get a StackOverflow Exception.  While the type has been updated, something in PocoSerializationStrategy is still trying to convert to Int32
System.AggregateException: One or more errors occurred. ---> System.OverflowException: Value was either too large or too small for an Int32.
                            at System.Convert.ToInt32(Int64 value)
                            at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
                            at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) System.OverflowException: Value was either too large or too small for an Int32.
                            at System.Convert.ToInt32(Int64 value)
                            at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
                            at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()<---

**Comment by ryangribble** [comment]
It could be another field that needs to change from `int` to `long`

Are you able to post a code snippet that reproduces it on a public repository?

**Comment by ryangribble** [comment]
It could be another field that needs to change from `int` to `long`

Are you able to post a code snippet that reproduces it on a public repository?

**Comment by bobbytreed** [comment]
I was just creating a github client in powershell and trying to query all events for a repo. 

As for the code, I didnt change it. I built directly from the cloned repo.

I'll admit maybe I did something wrong, but I really can't guess what.

**Comment by shiftkey** [comment]
> I was just creating a github client in powershell and trying to query all events for a repo.

If you can reproduce this against a public repository it'll help us to reproduce the issue on our end and identify what field returned from the API now overflows `int`.

**Comment by bobbytreed** [comment]
I fixed it locally by changing IssueEvent ID to a long as well.  I still hit an issue though with pagination.

Exception              : System.AggregateException: One or more errors occurred. ---> Octokit.ApiValidationException: In order to
                         keep the API fast for everyone, pagination is limited for this resource. Check the rel=last link relation
                         in the Link response header to see how far back you can traverse.
                            at Octokit.Connection.HandleErrors(IResponse response)

**Comment by shiftkey** [comment]
@bobbytreed some sample code would still be handy so we can understand how you're encountering issues

**Comment by bobbytreed** [comment]
$inmem = new-object OctoKit.Internal.InMemoryCredentialStore -ArgumentList ($cred)
$header = New-Object octokit.productheadervalue -ArgumentList "azure-function"
New-Variable -Name gitHubClient -Scope Global -Option AllScope -Force -Value $(new-object octokit.githubclient -ArgumentList $header, $inmem)
$options = New-Object octokit.apioptions
$options.pagesize = 100
$events = $gitHubClient.Issue.Events.GetAllForRepository("","", $options)

**Comment by shiftkey** [comment]
@bobbytreed apologies for the delay. I see that this last line doesn't have the owner and repo values:

```
$events = $gitHubClient.Issue.Events.GetAllForRepository("","", $options)
```

If this is reproducible on a public repository that'll greatly help to speed up reproducing this issue.

**Comment by mynkow** [comment]
This fails for me with the following exception:

**Comment by shiftkey** [comment]
This feels very similar to #2031, and while we have a PR started in #2037 this appears to have stalled. Gonna leave these both open for now and re-test the fix to confirm both issues are resolved.

**Comment by mijacobs** [comment]
> This feels very similar to #2031, and while we have a PR started in #2037 this appears to have stalled. Gonna leave these both open for now and re-test the fix to confirm both issues are resolved.

Any update on this? It looks like the PR still hasn't gone through.

**Comment by shiftkey** [comment]
@mijacobs it turns out that #2060 doesn't fix this, but #2092 will

**Comment by bifacil** [comment]
Some property need to be changed from int to long...

![image](https://github.com/octokit/octokit.net/assets/4572969/1df20635-2f46-4d5c-9b65-d5af93f5e541)

**Comment by bifacil** [comment]
Same issue here: #2889

**Comment by maddada** [comment]
Facing the same issue all of a sudden, any solutions?

` at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
   at Octokit.Connection.<Run>d__67'1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8'1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at LicenseManager.Controllers.Api.GithubReportsController.<GetPullRequestsReport>d__1.MoveNext() in <MyProjectName>\Controllers\Api\GithubReportsController.cs:line 79`

**Comment by bifacil** [comment]
> Facing the same issue all of a sudden, any solutions?
> 
> "Value was either too large or too small for an Int32."
> 
> `at System.Convert.ToInt32(Int64 value) at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) at Octokit.Connection.<Run>d__67'1.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Octokit.ApiConnection.<Get>d__8'1.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult() at LicenseManager.Controllers.Api.GithubReportsController.<GetPullRequestsReport>d__1.MoveNext() in <MyProjectName>\Controllers\Api\GithubReportsController.cs:line 79`

Update top 10.0.

It's solved.

https://github.com/octokit/octokit.net/issues/2889
