### ISSUE TITLE
a Server Error has occurred

### ISSUE THREAD

**Issue by bobbytreed** [octokit/octokit.net#2018]
Exception              : System.AggregateException: One or more errors occurred. ---> Octokit.ApiException: Server Error
                            at Octokit.Connection.HandleErrors(IResponse response)
                            at Octokit.Connection.<RunRequest>d__58.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                            at Octokit.Internal.ReadOnlyPagedCollection`1.<GetNextPage>d__3.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) Octokit.ApiException: Server Error
                            at Octokit.Connection.HandleErrors(IResponse response)
                            at Octokit.Connection.<RunRequest>d__58.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                            at Octokit.Internal.ReadOnlyPagedCollection`1.<GetNextPage>d__3.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
                         {
                           "message": "Server Error"
                         }

    $options = New-Object octokit.apioptions
    $options.PageSize = 100

    $issueRequest = New-Object Octokit.RepositoryIssueRequest
    $issueRequest.State = "All"
    $issueRequest.Filter = "All"
    
    $issues = gitHubClient.Issue.GetAllForRepository($repo.Id, $issueRequest, $options)

// $Repo is defined elsewhere and is valid

**Comment by hnrkndrssn** [comment]
Hey @bobbytreed, thanks for reporting this issue. 

I've tried replicating this issue on a few different repositories but I've not been able to get the same error response as you've posted. 

If this is reproducible on a public repository that you could provide us, that'll greatly help to speed up reproducing this issue.

Cheers,
Henrik

**Comment by bobbytreed** [comment]
Sure. https://github.com/MicrosoftDocs/azure-docs

**Comment by hnrkndrssn** [comment]
I wrote a test (same as sample above) to replicate this issue. 
First run it failed with the same `Server Error` response, so I ran it again in debug mode to see if I get some more details about why it failed **but** the test passed... 😕 

```
[IntegrationTest]
public async Task ServerErrorBugTest()
{
    var options = new ApiOptions
    {
        PageSize = 100
    };

    var issueRequest = new RepositoryIssueRequest
    {
        Filter = IssueFilter.All,
        State = ItemStateFilter.All
    };

    var repoIssues = await _issuesClient.GetAllForRepository("MicrosoftDocs", "azure-docs", issueRequest, options);
    Assert.NotNull(repoIssues);
}
```

**Comment by bobbytreed** [comment]
I'm still having the issue, so I'm not sure what to do.

**Comment by hnrkndrssn** [comment]
Ha! Reproduced the error after rebooting my machine 🙄

I doesn't really give any more details though... 😢 
![image](https://user-images.githubusercontent.com/1035315/66200849-491c4700-e6e5-11e9-8e12-1c5aaac7f4eb.png)

**Comment by shiftkey** [comment]
@hnrkndrssn what's interesting about the response is that it appears to have a valid `X-GitHub-Request-Id`, meaning it did reach the GitHub infrastructure, but it also has a status code of `502 Bad Gateway`. Not quite clear what it means, but the docs just suggest here that an "invalid response" was received from the GitHub infrastructure:

> The HyperText Transfer Protocol (HTTP) 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.

As this feels like something that we can't address in the client library, I'm inclined to close it if we provide enough details in the error that someone can provide the information to GitHub Support to help resolve their problem.

**Comment by hnrkndrssn** [comment]
Aye, it's an odd one...
I'd be happy to do a PR to provide some better error handling for this scenario

**Comment by shiftkey** [comment]
> I'd be happy to do a PR to provide some better error handling for this scenario

I'd love to review any improvements or ideas you have here

**Comment by hnrkndrssn** [comment]
Oddly enough, hitting [this URL](https://api.github.com/repos/MicrosoftDocs/azure-docs/issues?filter=all&state=all&sort=created&direction=desc&per_page=100) (which is the resulting URI in `octokit.net`, *but* without any `accept` headers) sometimes returns the same `Server error` response but other times it successfully returns the actual results... 😕

**Comment by hnrkndrssn** [comment]
I had an idea about how we could improve how we get error messages that we return for known error responses from the GitHub API _but_ it might be **over-engineering** things so I'll mention it here first before going any further.

In another product (that shall remain unnamed 😃) I'm involved in, we have an `ExceptionKnowledgeBase` that contains a list of "rules" that match different type of exceptions and accompanying summary/help text and links to docs.

```
ExceptionKnowledgeBase.AddRule(r => r.ExceptionIs<SomeException>(ex => ex.ErrorCode == "some_errorcode" && ex.Message.StartsWith("Some text"))
                .EntrySummaryIs("Some helpful summary")
                .EntryHelpTextIs("Some helpful help text")
                .EntryHelpLinkIs("https://some.link.to/docs"));
```
and then you use it like
```
if (ExceptionKnowledgeBase.TryInterpret(ex, out entry))
{
    error.ErrorMessage = entry.Summary;
    error.HelpText = entry.HelpText;
    error.HelpLink = entry.HelpLink;
}
```

We'd obviously need to tweak the functionality slightly for `octokit.net` to work in the same way as we currently handle known error responses from the GitHub API, e.g. 

https://github.com/octokit/octokit.net/blob/5ffc96995faa4ca0137521e628db2b7c862073b0/Octokit/Http/Connection.cs#L645-L653

Otherwise, we can just use another entry to the `_httpExceptionMap` in a similar way as we do for `HttpStatusCode.Forbidden` that calls the `GetExceptionForForbidden` and checks the body of the response for certain key phrases.

**Comment by shiftkey** [comment]
@hnrkndrssn if you can get me a recent `X-GitHub-Request-Id` I can dig into why these might be failing intermittently.

As for the proposed changes, I'm not 100% clear on what the resolution would be in this situation. I think, if we had problems that could be addressed in a self-service way, this format might help. But given the unclear and intermittent nature of this, for now I think we should provide more context or a more relevant exception type for `BadGateway`.

**Comment by hnrkndrssn** [comment]
Yea, it certainly feels like following the same format as we do for other `HttpStatusCode`s is a better solution for now.

I just re-ran my test that fails consistently and here is the `X-GitHub-Request-Id` that was returned in the response `D2F8:43F5:F2E02:119B8E:5DD3EE56`

**Comment by bobbytreed** [comment]
Good Morning All, Sorry for being absent, but good to see the conversation continued.  I'm getting this same error again today on another benign call.

```
currentBranches = await _client.Git.Reference.GetAll(From.owner, From.name);
```

Here is the stack trace

   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 707
   at Octokit.Connection.<RunRequest>d__60.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 682
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.Connection.<Run>d__59`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 666
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<GetPage>d__43`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 628
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<>c__DisplayClass18_0`1.<<GetAll>b__0>d.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 212
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Clients/ApiPagination.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DocIndex.Service.Helpers.PullRequestHelper.<CreateForkBranchIfNotExists>d__38.MoveNext() in C:\Users\robreed\source\docindex\src\service\Helpers\GitHubHelpers.cs:line 72
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DocIndex.Service.Helpers.PullRequestHelper.<StartPullRequest>d__40.MoveNext() in C:\Users\robreed\source\docindex\src\service\Helpers\GitHubHelpers.cs:line 118
   
Oddly, the request works when queried against my own repos, but not against other repos for which I have authorized my saml token, etc.

**Comment by bobbytreed** [comment]
Even more oddly, it works in all cases when invoked from PowerShell, but not from C#. I tested with .50 in C# and it failed, so I have a PS GitHubClient instance in my profile using the .32 version DLL (don't update it often).  The Git.Reference.Get call works from there to any repo.  I tried downgrading to .32 in C#, but it did not work.

**Comment by bobbytreed** [comment]
Still Getting this error. 

┌[ GLaDOS ] [  main ≣ ~3 -0 ! ]
└[~\source\docindex]> $prs = $gitHubClient.PullRequest.GetAllForRepository("MicrosoftDocs", "azure-docs-pr", $request)
┌[ GLaDOS ] [  main ≣ ~3 -0 ! ]
└[~\source\docindex]> $prs


Result                 :
Id                     : 671
Exception              : System.AggregateException: One or more errors occurred. ---> Octokit.ApiException: Server Error
                            at Octokit.Connection.HandleErrors(IResponse response)
                            at Octokit.Connection.<RunRequest>d__58.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) Octokit.ApiException: Server Error
                            at Octokit.Connection.HandleErrors(IResponse response)
                            at Octokit.Connection.<RunRequest>d__58.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
                         {
                           "message": "Server Error"
                         }
                         <---
                         

Happens in PowerShell and C# now, in GraphQL and normal.  The Repository has 164k pull requests, could that be an issue? 

Not understanding how commands that have worked for years could start failing.

**Comment by bobbytreed** [comment]
C# Stack Trace (.50)

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Octokit.GraphQL.Connection.<Run>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.GraphQL.Core.SimpleQuery`1.Runner.<RunPage>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Octokit.GraphQL.ConnectionExtensions.<Run>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DocIndex.Service.Helpers.GitHubHelper.<GetPullRequestsGraphQL>d__27.MoveNext() in

**Comment by jongio** [comment]
I ran into this same error today and don't seem to have a workaround.  Any thoughts on why we are getting this?
