### ISSUE TITLE
System.ArgumentException: Value 'transferred' is not a valid 'EventInfoState' enum value.

### ISSUE THREAD

**Issue by terrajobst** [octokit/octokit.net#2023]
I'm calling `EventInfo.Event.Value`, which apparently doesn't work for issues that were transferred:

```
Unhandled exception. System.ArgumentException: Value 'transferred' is not a valid 'EventInfoState' enum value.
   at Octokit.StringEnum`1.ParseValue() in C:\Users\shiftkey\src\octokit.net\Octokit\Models\Response\StringEnum.cs:line 146
   at Octokit.StringEnum`1.get_Value() in C:\Users\shiftkey\src\octokit.net\Octokit\Models\Response\StringEnum.cs:line 45
   at ApiReviewList.Reports.ApiReviewFeedback.<GetAsync>g__IsApiEvent|1_1(EventInfo eventInfo) in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 42
   at ApiReviewList.Reports.ApiReviewFeedback.<>c__DisplayClass1_0.<GetAsync>b__10(EventInfo e) in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 57
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at ApiReviewList.Reports.ApiReviewFeedback.<GetAsync>g__GetApiEvents|1_2(IEnumerable`1 events, SortedSet`1 dateSet)+MoveNext() in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 57
   at ApiReviewList.Reports.ApiReviewFeedback.GetAsync(IEnumerable`1 dates) in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 139
   at ApiReviewList.Reports.ApiReviewSummary.GetAsync(IEnumerable`1 dates) in P:\api-review-list\create-past-reviews\Reports\ApiReviewSummary.cs:line 25
   at create_past_reviews.Program.Main(String[] args) in P:\api-review-list\create-past-reviews\Program.cs:line 20
   at create_past_reviews.Program.<Main>(String[] args)
```

**Comment by shiftkey** [comment]
@terrajobst probably not going to be able to look at this until the weekend, but if you can get a reproducible failure out of it'll save me a lot of time to verify the fix.

**Comment by shiftkey** [comment]
https://github.com/octokit/octokit.net/blob/5d4df9c7f0bf85a659b70381926d09d24f9bb896/Octokit/Models/Response/EventInfo.cs#L81

This is the type that probably needs a new `transferred` state

**Comment by shiftkey** [comment]
@terrajobst to nerd-snipe you into helping me out a bit, if you wanted to open a PR with that new field it'll generate a new NuGet package on [the beta feed](https://github.com/octokit/octokit.net#beta-packages) which you can then install and verify the fix on your end.

**Comment by hnrkndrssn** [comment]
If no one gets to this, I can get a PR together tonight. 

Also, the [Events](https://developer.github.com/v3/issues/events/) docs doesn't include a `transferred` event type...
