### ISSUE TITLE
System.ArgumentException: Value 'head_ref_force_pushed' is not a valid 'EventInfoState' enum value

### ISSUE THREAD

**Issue by terrajobst** [octokit/octokit.net#2025]
Similar #2023:

```
Unhandled exception. System.ArgumentException: Value 'head_ref_force_pushed' is not a valid 'EventInfoState' enum value.
   at Octokit.StringEnum`1.ParseValue() in C:\Users\shiftkey\src\octokit.net\Octokit\Models\Response\StringEnum.cs:line 146
   at Octokit.StringEnum`1.get_Value() in C:\Users\shiftkey\src\octokit.net\Octokit\Models\Response\StringEnum.cs:line 45
   at ApiReviewList.Reports.ApiReviewFeedback.<GetAsync>g__IsApiEvent|1_1(EventInfo eventInfo) in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 46
   at ApiReviewList.Reports.ApiReviewFeedback.<>c__DisplayClass1_0.<GetAsync>b__11(EventInfo e) in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 61
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at ApiReviewList.Reports.ApiReviewFeedback.<GetAsync>g__GetApiEvents|1_2(IEnumerable`1 events, SortedSet`1 dateSet)+MoveNext() in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 61
   at ApiReviewList.Reports.ApiReviewFeedback.GetAsync(IEnumerable`1 dates) in P:\api-review-list\create-past-reviews\Reports\ApiReviewFeedback.cs:line 163
   at ApiReviewList.Reports.ApiReviewSummary.GetAsync(IEnumerable`1 dates) in P:\api-review-list\create-past-reviews\Reports\ApiReviewSummary.cs:line 25
   at create_past_reviews.Program.Main(String[] args) in P:\api-review-list\create-past-reviews\Program.cs:line 20
   at create_past_reviews.Program.<Main>(String[] args)
```

**Comment by hnrkndrssn** [comment]
I can add this in my PR for adding the `transferred` event type
