### ISSUE TITLE
Uploading large asset files for release fails

### ISSUE THREAD

**Issue by macsux** [octokit/octokit.net#2045]
Uploading large files (~30mb) seems to fail. I can upload this through the browser no problem. Works fine with smaller files.

``` 
var stream = File.OpenRead(zipPackageLocation);
var releaseAssetUpload = new ReleaseAssetUpload(PackageZipName, "application/zip", stream, TimeSpan.FromHours(1));
var releaseAsset = await client.Repository.Release.UploadAsset(release, releaseAssetUpload);
```

I've debugged the internal error, and traced the inner error to the one below:

```
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteAsync|210_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\HttpClientAdapter.cs:line 205
```

**Comment by shiftkey** [comment]
@macsux does it seem to be failing due to the timeout being hit (i.e. takes an hour to throw the error) or does it error fairly quickly (which might be a different issue at play)?

> I can upload this through the browser no problem.

It's not clear to me what you're using to run the code or upload the files - .NET Framework, .NET Core, Chrome,  Firefox, whatever. Can you elaborate a bit more here?

**Comment by macsux** [comment]
Using .NET Core 3.0. When testing manual upload using chrome.

It seems to vary, it doesn't take an hour, seems to never go over 90 seconds, and high-level exception is operation is canceled - I did internal step through to get to inner one. Having said that my pipe is really fast - when uploading through browser, 30mb zip goes in like 5 seconds, while code takes MUCH longer to timeout. I've had it succeed sometimes, but only like 5% of the times I try it.

**Comment by macsux** [comment]
Using Octokit 0.36

**Comment by macsux** [comment]
Seems like uploading interactively through the browser uses AWS for asset upload (https://github-production-release-asset-2e65be.s3.amazonaws.com/) whereas using Octokit uses API endpoint such as https://uploads.github.com/repos/macsux/certificate-buildpack/releases/21572092/assets{?name,label}

This potentially explains the difference in behavior and upload speed.
