### ISSUE TITLE
Configure Octokit to trust remote certificate

### ISSUE THREAD

**Issue by liiri** [octokit/octokit.net#2097]
Hi,

I've installed Github Enterprise on a VM and am accessing it via IP with ssl under self signed certificate. I do not plan to assign a domain or a custom certificate.

How can I query the server using Octokit?

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
  at at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
  at at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
  at at System.Net.Security.SslStream.ThrowIfExceptional()
  at at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
  at at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
  at at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
  at at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
  at at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  at at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\HttpClientAdapter.cs:205
```

My code:

```
var gitHubClient = new GitHubClient(new ProductHeaderValue("product"), new Uri("https://<my ip>"))
{
   Credentials = new Octokit.Credentials("admin", "...")
};
var me = await client.User.Current()
```

**Comment by shiftkey** [comment]
@liiri this is something outside of Octokit itself, but you need to configure your app to trust a self-signed certificate when it encounters it by adding this code: https://stackoverflow.com/a/526730/1363815

```
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
```

This is not recommended for production usage, but should help with your testing.

**Comment by liiri** [comment]
Most client apis support such configuration on their level. Also many organizations use untrusted certificatesbin their production. You should consider supporting this configuration.

**Comment by shiftkey** [comment]
Certificate verification is not controlled by Octokit, and I don't see the value of duplicating APIs that exist in the .NET Framework and introducing potential confusion when they are both used.

**Comment by liiri** [comment]
I'll just add that trusting a single certificate is very different approach than trusting all.
