### ISSUE TITLE
System.OverflowException: Value was either too large or too                          small for an Int32.

### ISSUE THREAD

**Issue by bobbytreed** [octokit/octokit.net#2119]
While trying to get all issue events for a large repo. I received the following message. I'm guessing I'll have to page it or something, but this is definitely not very descriptive.

System.AggregateException: One or more errors occurred. ---> System.OverflowException: Value was either too large or too
                         small for an Int32.
                            at System.Convert.ToInt32(Int64 value)
                            at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
                            at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) System.OverflowException: Value was either too large or too small for an Int32.
                            at System.Convert.ToInt32(Int64 value)
                            at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
                            at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy)
                            at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response)
                            at Octokit.Connection.<Run>d__57`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()<---

**Comment by bobbytreed** [comment]
dup

**Comment by bobbytreed** [comment]
duplicate of #1979 This is now appears to be resolved.  Thanks!!!

**Comment by greendalf** [comment]
hello...i have a similar problem with my unturned server rocket plugin "kits"

OverflowException: Value was either too large or too small for an Int32.
at System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00057] in <9577ac7a62ef43179789031239ba8798>:0
at System.Int32.Parse (System.String s, System.Globalization.NumberStyles style, System.IFormatProvider provider) [0x0000e] in <9577ac7a62ef43179789031239ba8798>:0
at System.Xml.XmlConvert.ToInt32 (System.String s) [0x00007] in <1d98d70bb7d8453b80c25aa561fdecd1>:0
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderKitsConfiguration.Read6_NullableOfInt32 (System.Boolean checkType) [0x00027] in <48040cf479854ce499b8aff7dcbfdd30>:0
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderKitsConfiguration.Read7_Kit (System.Boolean isNullable, System.Boolean checkType) [0x0043d] in <48040cf479854ce499b8aff7dcbfdd30>:0
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderKitsConfiguration.Read8_KitsConfiguration (System.Boolean isNullable, System.Boolean checkType) [0x00235] in <48040cf479854ce499b8aff7dcbfdd30>:0
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderKitsConfiguration.Read9_KitsConfiguration () [0x00050] in <48040cf479854ce499b8aff7dcbfdd30>:0
at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <9577ac7a62ef43179789031239ba8798>:0
Rethrow as InvalidOperationException: There is an error in XML document (19, 7).
at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x0011b] in <1d98d70bb7d8453b80c25aa561fdecd1>:0
at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1d98d70bb7d8453b80c25aa561fdecd1>:0
at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1d98d70bb7d8453b80c25aa561fdecd1>:0
at Rocket.Core.Assets.XMLFileAsset`1[T].Load (Rocket.API.AssetLoaded`1[T] callback) [0x00026] in <de2b2fb669424d2dae1c4b01e1864fe9>:0
Rethrow as Exception: Failed to deserialize XMLFileAsset: Plugins/Kits/Kits.configuration.xml
at Rocket.Core.Assets.XMLFileAsset`1[T].Load (Rocket.API.AssetLoaded`1[T] callback) [0x00073] in <de2b2fb669424d2dae1c4b01e1864fe9>:0
at Rocket.Core.Assets.XMLFileAsset`1[T]..ctor (System.String file, System.Type[] extraTypes, fr34kyn01535.Kits.KitsConfiguration defaultInstance) [0x0002a] in <de2b2fb669424d2dae1c4b01e1864fe9>:0
at Rocket.Core.Plugins.RocketPlugin`1[RocketPluginConfiguration]..ctor () [0x000ad] in <de2b2fb669424d2dae1c4b01e1864fe9>:0
at fr34kyn01535.Kits.Kits..ctor () [0x00000] in <427e31678a3d487281f1fd370abd75ac>:0
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()
(Filename: <9577ac7a62ef43179789031239ba8798> Line: 0)
NullReferenceException: Object reference not set to an instance of an object
at Rocket.Core.Plugins.RocketPlugin`1[RocketPluginConfiguration].LoadPlugin () [0x00012] in <de2b2fb669424d2dae1c4b01e1864fe9>:0
at Rocket.Core.Plugins.RocketPlugin.OnEnable () [0x00000] in <de2b2fb669424d2dae1c4b01e1864fe9>:0
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()
(Filename: <de2b2fb669424d2dae1c4b01e1864fe9> Line: 0)
