### ISSUE TITLE
Cannot create issue on repo that I own under my user account

### ISSUE THREAD

**Issue by danijeljw-RPC** [octokit/octokit.net#2363]
I am trying to create an issue. I have followed the guide.

Replacing `my-gh-username`, `ghp_my-gh-oauth-token` and `my-gh-repo` with the values they represent, this is the code I am using:

```csharp
using Octokit;
using System.Threading.Tasks;

namespace CreateNewIssue
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var client = new GitHubClient(new ProductHeaderValue("D61F5FB7-DC3D-4A0C-B790-F13474A57624"));
            var tokenAuth = new Credentials("ghp_my-gh-oauth-token");
            client.Credentials = tokenAuth;

            var createIssue = new NewIssue("this thing doesn't work");
            var issue = await client.Issue.Create("my-gh-username", "my-gh-repo", createIssue);
        }
    }
}
```

This is the error I get:
```
Octokit.NotFoundException
  HResult=0x80131500
  Message=Not Found
  Source=Octokit
  StackTrace:
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 700
   at Octokit.Connection.<RunRequest>d__60.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 681
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__59`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 666
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__23`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 295
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CreateNewIssue.Program.<Main>d__0.MoveNext() in C:\Users\user\source\repos\GitHub.Tools\CreateNewIssue\Program.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]
    CreateNewIssue.Program.Main(string[]) in Program.cs
```

Why is it not creating the issue as expected?

**Comment by danijeljw-RPC** [comment]
Sorry!

I did further testing and it requires the following minimum as a permission:

- [ ] **public_repo** Access public repositories

It may be helpful to add this to the documentation.
