### ISSUE TITLE
Pull request creation fails when adding .github folder

### ISSUE THREAD

**Issue by hiren929** [octokit/octokit.net#2387]
While creating a pull request against master branch using latest version (0.50.0) of Octokit lib, it throws following error if feature branch (branch1) has .github directory.

Error:
{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/enterprise/3.1/rest/reference/pulls#create-a-pull-request"}

Creation of Pull request works if branch1 has .any_other_dir_name, but fails when .github dir has been added by the feature branch.

Code:
var client = new GitHubClient(
                new ProductHeaderValue("branch1"),
                new InMemoryCredentialStore(new Credentials(accessToken, AuthenticationType.Oauth)),
                gheURI);

 await client.PullRequest.Create(remote.Id, new NewPullRequest(prTitle, "branch1", "master"));

Full stack trace:
Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 703
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in 
.
.
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/enterprise/3.1/rest/reference/pulls#create-a-pull-request"}

Please help. Thanks.

**Comment by hiren929** [comment]
Figure it out. OAuth app was missing "workflow" scope.
