### ISSUE TITLE
[BUG]: .NET 7.0 causes ArgumentException in client.Repository.Content.DeleteFile

### ISSUE THREAD

**Issue by DotNet-Ninja** [octokit/octokit.net#2659]
### What happened?

Using client.Repository.Content.DeleteFile(org, repo, filePath, DeleteFileRequest) of GitHubClient throws an ArgumentException - The value cannot be null or empty. (Parameter 'mediaType') when invoked in an application compiled using .Net 7.0.  This previously worked in .Net 6.0 (I verified that simply reverting my project back to 6.0 resolves the issue with all 3 of the following versions of Ocotkit.net Octokit.net 4.0.0, 4.0.3, 4.0.4).

Background: We identified an issue in our application where a function that had previously worked was now failing and upon looking into the logs found the exception: System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType').  After some digging, realizing that our code had not changed we began looking into what had and found that we had recently upgraded to .Net 7.0 and Octokit 4.0.3.  We tried rolling back the Octokit change and upgrading to the latest version and then reverted to .Net 6.0 which solved the issue.

I have put together a sample application that demonstrates this behavior here: https://github.com/DotNet-Ninja/SampleRepository that you can use to replicate the issue.  There are instructions/details in the readme file in that repo as far as how to set up the project and replicate the issue. 

### Versions

Octokit.net 4.0.0, 4.0.3, 4.0.4

### Relevant log output

```shell
System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at Octokit.Internal.HttpClientAdapter.BuildRequestMessage(IRequest request) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/HttpClientAdapter.cs:line 144
   at Octokit.Internal.HttpClientAdapter.Send(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/HttpClientAdapter.cs:line 47
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 679
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
   at Octokit.Connection.Delete(Uri uri, Object data) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 563
   at Program.Main(String[] args) in C:\Code\SampleRepository\src\SampleRepository\Program.cs:line 34
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by v-jasric** [comment]
Running into this in 5.0.4. Any updates for DeleteFile?

**Comment by IvanJosipovic** [comment]
I'm also facing this issue.

**Comment by mouradchnaiti** [comment]
I'm also facing this issue.
