### ISSUE TITLE
[BUG]: Value 'branch_protection_configuration' is not a valid 'AppEvent' enum value.

### ISSUE THREAD

**Issue by ronimizy** [octokit/octokit.net#2809]
### What happened?

I have a serialization step in web hook processing pipeline (for logging purposes).
When trying to serialize IssueCommentEvent instance received by ProcessIssueCommentWebhookAsync method `System.ArgumentException` being thrown.
It says:
Value 'branch_protection_configuration' is not a valid 'AppEvent' enum value.

### Versions

Octokit 9.0.0
Octokit.Webhooks.AspNetCore 2.0.5

### Relevant log output

```shell
Octokit.Webhooks.WebhookEventProcessor Exception processing GitHub event.
Newtonsoft.Json.JsonSerializationException: Error getting value from 'Value' on 'Octokit.Webhooks.Extensions.StringEnum`1[Octokit.Webhooks.Models.AppEvent]'.
 ---> System.ArgumentException: Value 'branch_protection_configuration' is not a valid 'AppEvent' enum value.
   at Octokit.Webhooks.Extensions.StringEnum`1.ParseValue()
   at Octokit.Webhooks.Extensions.StringEnum`1.get_Value()
   at lambda_method473(Closure, Object)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronimizy** [comment]
my bad, this issue would be probably more appropriate to be put in https://github.com/octokit/webhooks.net
