### ISSUE TITLE
[BUG]: A JSON web token could not be decoded

### ISSUE THREAD

**Issue by greggjensencart** [octokit/octokit.net#2833]
### What happened?

Any chance you have an example of generating the GitHub App JWT?  I keep running into the following error:

```
Octokit.AuthorizationException: A JSON web token could not be decoded
   at Octokit.Connection.HandleErrors(IResponse response) in /_/Octokit/Http/Connection.cs:line 766
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 747
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 732
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters)
```

Here is the code I am using. I have tried 10 variations and libraries.

```csharp
	var pem = @"
-----BEGIN RSA PRIVATE KEY-----
PRIVATE KEY
-----END RSA PRIVATE KEY-----
";
	using var rsa = RSA.Create();
	rsa.ImportFromPem(pem);

	var signingCredentials = new SigningCredentials(new RsaSecurityKey(rsa), SecurityAlgorithms.RsaSha256)
	{
		CryptoProviderFactory = new CryptoProviderFactory { CacheSignatureProviders = false }
	};

	var now = DateTimeOffset.Now;

	var jwt = new JwtSecurityToken(
		issuer: "111111",
		claims: new Claim[]{
			new ("iat",now.AddMinutes(-1).ToUnixTimeSeconds().ToString(), ClaimValueTypes.Integer)
		},
		expires: now.AddMinutes(10).Date,
		signingCredentials: signingCredentials
	);

	token = new JwtSecurityTokenHandler().WriteToken(jwt);

       _githubAppClient = new GitHubClient(new ProductHeaderValue("MyApp"), new InMemoryCredentialStore(credentials));
       var app = await _githubAppClient.GitHubApps.GetCurrent();
```

### Versions

OctokIt 8.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shem8** [comment]
I have the same problem, it was because the new version of Node and starting using the new `fetch` api: https://github.com/nodejs/node/releases/tag/v18.0.0

What I'm doing right now is to add `--no-experimental-fetch` when running node, but this should be fixed
