### ISSUE TITLE
[BUG]: Github Enterprise License API fails when parsing temp license

### ISSUE THREAD

**Issue by AlexanderBrehm-hps** [octokit/octokit.net#2903]
### What happened?

Hey Team,

I'm getitng this error when attempting to use the Enterprise.License.Get() method in OcktoKit
<img width="547" alt="image" src="https://github.com/octokit/octokit.net/assets/8270013/63807510-5966-405f-8672-cb018e527b4c">

This seems to be because my license is currently a temp one given out by Github/Microsoft with both "unlimited" seats and seats_available
<img width="1162" alt="image" src="https://github.com/octokit/octokit.net/assets/8270013/5bad86f2-2155-4534-ad1b-bcb24f09774f">

I suspect this is then causing the license info class to have issues when attempting to parse the seats and seats_available properties, since those are both strings in my current license as opposed to being the INTs requested by the LicenseInfo object
<img width="957" alt="image" src="https://github.com/octokit/octokit.net/assets/8270013/eb5ffff4-c7d7-4f3f-ba6b-8d013ca4aacb">

I ended up hacking around it to prove it.
<img width="1424" alt="image" src="https://github.com/octokit/octokit.net/assets/8270013/38a08f8d-ee7b-4578-abf2-c9912768c3dc">

I'm not sure if this actually needs to be fixed because most people won't have the evaluation license, but I did want to bring it to your all's attention as it could cause issues for other people and you might want to consider making an update to your code.

### Versions

Github Enterprise 3.11.5
Octokit v 10.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexanderBrehm-hps** [comment]
Here's the stack trace as well
```
System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1401
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1492
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 596
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /_/Octokit/Http/JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__67`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Hps.Tools.Management.HPSGithubClient.License_Get() in C:\code\devops\Hps.Tools.Management\Hps.Tools.Management\HPSGithubClient.cs:line 159
---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1401
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1492
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 596
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /_/Octokit/Http/JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__67`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()<---
```
