### ISSUE TITLE
[BUG]: Error deserializing issue comments

### ISSUE THREAD

**Issue by brantburnett** [octokit/octokit.net#2927]
### What happened?

I've begun noticing errors deserializing the comment ID number when receiving issue webhooks. The value appears to be an `int` in the models but it seems GitHub has finally crossed the threshold and needs a `long`. The log was for a comment created webhook request.

Note: This is very similar to bug #2889 fixed in 10.0.0, but on comment IDs rather than issue IDs. 

### Versions

10.0.0 but bug appears to still be present in the main branch

### Relevant log output

```shell
JSON integer 2147666618 is too large or small for an Int32. Path 'comment.id', line 1, position 4002.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at CenterEdgeBot.Events.ActivityPayloadParser.ParseActivityPayload(String payloadType, String payloadText) in /jenkins/workspace/DevOps_CenterEdgeBot_main/src/CenterEdgeBot/Events/ActivityPayloadParser.cs:line 43
   at CenterEdgeBot.Events.GitHubWebHookProcessor.ProcessGitHubWebHookPayloadAsync(String payloadType, String payloadText) in /jenkins/workspace/DevOps_CenterEdgeBot_main/src/CenterEdgeBot/Events/GitHubWebHookProcessor.cs:line 43
   at CenterEdgeBot.GitHubLambda.HandleGitHubWebHookAsync(APIGatewayProxyRequest apiGatewayProxyRequest, ILambdaContext lambdaContext) in /jenkins/workspace/DevOps_CenterEdgeBot_main/src/CenterEdgeBot/GitHubLambda.cs:line 71
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidBoike** [comment]
Additionally, all the methods on `IIssueCommentsClient` use an `int` for issue number, such as `Task<IReadOnlyList<IssueComment>> GetAllForIssue(string owner, string name, int number)` so it seems like the `int` to `long` transition needs to be plumbed out in quite a few places.

**Comment by AlmirJNR** [comment]
why don't we change all `int` to `long` to avoid this in the future? i don't know if it is possible or if it is, then why things wasn't like this already?

**Comment by AlmirJNR** [comment]
As @DavidBoike said, it seams like the problem (mine at least) is in the property in`[Octokit.IssueComment.Id]` and every json response that i'm getting is returning values greater than the `int.MaxValue`

example of the responses that i'm getting `List<Octokit.IssueComment>`
```json
[{
    "url": "https://redacted/issues/comments/2148124527",
    "html_url": "https://redacted/pull/1#issuecomment-2148124527",
    "issue_url": "https://redacted/issues/1",
    "id": 2148124527,
    "node_id": redacted,
    "user": {
      "login": "AlmirJNR",
      "id": redacted,
      "node_id": redacted,
      "avatar_url": redacted,
      "gravatar_id": "",
      "url": redacted,
      "html_url": redacted,
      "followers_url": redacted,
      "following_url": redacted,
      "gists_url": redacted,
      "starred_url": redacted,
      "subscriptions_url": redacted,
      "organizations_url": redacted,
      "repos_url": redacted,
      "events_url": redacted,
      "received_events_url": redacted,
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-06-04T18:12:02Z",
    "updated_at": "2024-06-04T18:12:02Z",
    "author_association": "OWNER",
    "body": "AAAAAAAAAAAAAAAAAAAAA",
    "reactions": {
      "url": redacted,
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
...]
```

**Comment by wolfcomp** [comment]
Looking at the response schema for comments on issues, you will see that it lists the type as `int64` https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28

This is something that should be expressly fixed due to it breaking actions that rely on this library for build processing.

**Comment by JimSuplizio** [comment]
+1 here, I'm seeing the same thing trying to deserialize. 

It's the IssueComment's Id, in [Octokit/Models/Response/IssueComment.cs#L30](https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/IssueComment.cs#L30), being an int. The GitHub Actions payload has "id": 2152686870 which is > Int32 max or 2147483647.

This was the same thing that happened with [Issues 4 months ago](https://github.com/octokit/octokit.net/issues/2889). 

@nickfloyd, I'm curious as to how this is getting changed internally without Octokit having an update ready?

**Comment by nickfloyd** [comment]
> [@nickfloyd](https://github.com/nickfloyd), I'm curious as to how this is getting changed internally without Octokit having an update ready?

Hey @JimSuplizio,

There are a few reasons.  

While Octokit.net has served the community well over the years, the static nature of it makes it challenging for the small team and community to make sure it's synchronized with the overwhelming number of changes that are being made on a daily basis to GitHub's OpenAPI descriptions.  So as a team, we have had to [make decisions](https://github.com/octokit/.github/blob/main/community/prioritization_response.md) to maintain this and build for the future through [Generative SDKs](https://github.blog/2024-01-03-our-move-to-generated-sdks/).

These issues experienced here are not present in our [.NET Generated SDK](https://github.com/octokit/dotnet-sdk) - which is regenerated nightly. I'd encourage you to give that next generation of SDK a shot and let us know what you think.  The generated SDK (GitHub.Octokit.SDK) already has things like client side rate limiting and apps auth with automatic token refresh - two features that are not currently present in Octokit.net.

We'll continue to maintain this SDK but I just wanted to let you know where we are headed.

**Comment by JimSuplizio** [comment]
> > [@nickfloyd](https://github.com/nickfloyd), I'm curious as to how this is getting changed internally without Octokit having an update ready?
> 
> Hey @JimSuplizio,
> 
> There are a few reasons.
> 
> While Octokit.net has served the community well over the years, the static nature of it makes it challenging for the small team and community to make sure it's synchronized with the overwhelming number of changes that are being made on a daily basis to GitHub's OpenAPI descriptions. So as a team, we have had to [make decisions](https://github.com/octokit/.github/blob/main/community/prioritization_response.md) to maintain this and build for the future through [Generative SDKs](https://github.blog/2024-01-03-our-move-to-generated-sdks/).
> 
> These issues experienced here are not present in our [.NET Generated SDK](https://github.com/octokit/dotnet-sdk) - which is regenerated nightly. I'd encourage you to give that next generation of SDK a shot and let us know what you think. The generated SDK (GitHub.Octokit.SDK) already has things like client side rate limiting and apps auth with automatic token refresh - two features that are not currently present in Octokit.net.
> 
> We'll continue to maintain this SDK but I just wanted to let you know where we are headed.

I've looked at the .NET Generated SDK but I'm going to be delaying anything until the SDK is out of alpha. Mainly because it would require me to effectively re-code/extensively change my GitHub event processor.

**Comment by joscol** [comment]
This is not fully fixed, I'm still seeing issues with some PRs.  I think the problem is the InReplyToId of PullRequestComment ( https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/PullRequestReviewComment.cs ) which is still an int.

**Comment by nickfloyd** [comment]
Hey @joscol looks like you're right, great catch.  I'll do another sweep.  Apologies for the trouble.

**Comment by JimSuplizio** [comment]
> Hey @joscol looks like you're right, great catch. I'll do another sweep. Apologies for the trouble.

@nickfloyd was the release of [13.0.1](https://www.nuget.org/packages/Octokit/13.0.1) the result of fixing the issue(s) @joscol mentioned above?
