### ISSUE TITLE
cleanup inside RepositoriesClientTests is failing on build server

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#578]
This is the output from a CI run:

```
RepositoriesClientTests+TheCreateMethodForUser.CreatesARepositoryWithAGitignoreTemplate [FAIL]
   System.AggregateException : One or more errors occurred.
   ---- Octokit.ApiException : Server Error
   Stack Trace:
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
      at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
      at System.Threading.Tasks.Task`1.get_Result()
      c:\projects\octokit-net\Octokit.Tests.Integration\Clients\RepositoriesClientTests.cs(318,0): at RepositoriesClientTests.TheCreateMethodForUser.Dispose()
      at Xunit.Sdk.LifetimeCommand.Execute(Object testClass)
      at Xunit.Sdk.ExceptionAndOutputCaptureCommand.Execute(Object testClass)
   ----- Inner Stack Trace -----
      c:\projects\octokit-net\Octokit\Http\Connection.cs(404,0): at Octokit.Connection.HandleErrors(IResponse response)
      c:\projects\octokit-net\Octokit\Http\Connection.cs(381,0): at Octokit.Connection.<RunRequest>d__18`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      c:\projects\octokit-net\Octokit\Http\Connection.cs(369,0): at Octokit.Connection.<Run>d__14`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      c:\projects\octokit-net\Octokit\Http\ApiConnection.cs(339,0): at Octokit.ApiConnection.<GetPage>d__2e`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      c:\projects\octokit-net\Octokit\Http\ApiConnection.cs(132,0): at Octokit.ApiConnection.<>c__DisplayClassd`1.<<GetAll>b__c>d__f.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      c:\projects\octokit-net\Octokit\Clients\ApiPagination.cs(25,0): at Octokit.ApiPagination.<GetAllPages>d__1`1.MoveNext()
```

I can't repro this, but it's occurring in the cleanup code so I think it's data-related...

```
// Clean up the repos.
public void Dispose()
{
    var github = new GitHubClient(new ProductHeaderValue("OctokitTests"))
    {
        Credentials = Helper.Credentials
    };
    var repositories = github.Repository.GetAllForCurrent().Result;

    foreach (var repository in repositories)
    {
        try
        {
            github.Repository.Delete(repository.Owner.Login, repository.Name).Wait();
         }
         catch (Exception) { }
    }
}
```

**Comment by shiftkey** [comment]
I've removed this method in #656 as it was no longer necessary.

If it comes back somehow I'll try and grab a Fiddler log of the problem
