### ISSUE TITLE
Can't deploy Paket.exe to GitHub anymore

### ISSUE THREAD

**Issue by forki** [octokit/octokit.net#944]
![image](https://cloud.githubusercontent.com/assets/57396/10578545/18f0e324-7673-11e5-868f-3dd3e2d12216.png)

I'm getting validation exceptions when I try to publish to github. Did the github API change again?
Manual upload works.

**Comment by shiftkey** [comment]
Ugh, we really should have the response payload in that error message so it's easier to follow.

Can you put Fiddler in between and see what the response payload looks like?

I'm not aware of anything recent with the Releases API changing, but I can bug them if we spot something weird.

**Comment by forki** [comment]
Ok. I tried again. Now it works again. But earlier today I had 5 failed deploys from 2 machines. Maybe something was flaky.

**Comment by naveensrinivasan** [comment]
I was trying to deploy Paket to forked repo and I got this. I agree I would prefer Response payload.

```
Paket.exe 2.15.6 is up to date.
Paket version 2.15.6.0
1 second - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target ReleaseGitHub:
<== ReleaseGitHub

The resulting target order is:
 - ReleaseGitHub
Starting Target: ReleaseGitHub
C:\Program Files (x86)\Git\bin\git.exe remote -v
C:\Program Files (x86)\Git\bin\git.exe add . --all

C:\Program Files (x86)\Git\bin\git.exe commit -m "Bump version to 2.15.6"
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
On branch master
C:\Program Files (x86)\Git\bin\git.exe status
C:\Program Files (x86)\Git\bin\git.exe --version
C:\Program Files (x86)\Git\bin\git.exe --version
Username for 'https://github.com': naveensrinivasan
Password for 'https://naveensrinivasan@github.com':
Everything up-to-date
C:\Program Files (x86)\Git\bin\git.exe tag 2.15.6
Username for 'https://github.com': naveensrinivasan
Password for 'https://naveensrinivasan@github.com':
Everything up-to-date
Running build failed.
Error:
System.AggregateException: One or more errors occurred. ---> Octokit.NotFoundExc
eption: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in c:\dev\octokit.net\
Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__2b.MoveNext() in c:\dev\octokit.net\Octo
kit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.Connection.<Run>d__27`1.MoveNext() in c:\dev\octokit.net\Octokit\H
ttp\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.ApiConnection.<Post>d__12`1.MoveNext() in c:\dev\octokit.net\Octok
it\Http\ApiConnection.cs:line 0
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](Cancella
tionToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 com
putation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 483
---> (Inner Exception #0) Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in c:\dev\octokit.net\
Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__2b.MoveNext() in c:\dev\octokit.net\Octo
kit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.Connection.<Run>d__27`1.MoveNext() in c:\dev\octokit.net\Octokit\H
ttp\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.ApiConnection.<Post>d__12`1.MoveNext() in c:\dev\octokit.net\Octok
it\Http\ApiConnection.cs:line 0<---

System.AggregateException: One or more errors occurred. ---> Octokit.NotFoundExc
eption: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in c:\dev\octokit.net\
Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__2b.MoveNext() in c:\dev\octokit.net\Octo
kit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.Connection.<Run>d__27`1.MoveNext() in c:\dev\octokit.net\Octokit\H
ttp\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.ApiConnection.<Post>d__12`1.MoveNext() in c:\dev\octokit.net\Octok
it\Http\ApiConnection.cs:line 0
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](Cancella
tionToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 com
putation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 483
---> (Inner Exception #0) Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in c:\dev\octokit.net\
Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__2b.MoveNext() in c:\dev\octokit.net\Octo
kit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.Connection.<Run>d__27`1.MoveNext() in c:\dev\octokit.net\Octokit\H
ttp\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Octokit.ApiConnection.<Post>d__12`1.MoveNext() in c:\dev\octokit.net\Octok
it\Http\ApiConnection.cs:line 0<---


---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
No target was successfully completed
---------------------------------------------------------------------
```
